language: go
python:
  - 3.9

branches:
  only:
    - master

services:
  - docker

stages:
  - Test
  # - Github Packages Deploy

jobs:
  include:
    - stage: Test
      before_script:
        - cp ./build/env/.env.sample ./build/env/.env
        - go get github.com/mattn/goveralls
      script:
        - make ci_check_tests
        - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci

    # - stage: Github Packages Deploy
    #   if: (NOT type IN (pull_request)) AND (branch = master)
    #   env: TAG=$(date +%d%m%Y%H%M%S)
    #   script: make docker_tag_and_push
